### ISSUE TITLE
How can I add custom functions?

### ISSUE THREAD

**Issue by Personuo** [theor/BurstExpressions#1]
Hi, this tool is really cool and great! tool!
How can I add custom  functions? For example "lerp" 
thank you!

**Comment by theor** [comment]
Thanks !
First declare the new function: go here
https://github.com/theor/BurstExpressions/blob/af546238ea8e9b9621bf9087b034fd3bd3c79cd6/Runtime/Runtime/EvalOp.cs#L21
Add a new enum value:
```cs
[OpDescription("lerp(a,b,t)", "Interpolates between the points a and b by the interpolant t")]
Lerp_3,
```

Then the function implementation itself: go here https://github.com/theor/BurstExpressions/blob/af546238ea8e9b9621bf9087b034fd3bd3c79cd6/Runtime/Runtime/Evaluator.cs#L148 and add the matching case:
```cs
            case EvalOp.Lerp_3:
                        impl.Push(math.lerp(impl.Pop(), impl.Pop(), impl.Pop()));
                        break;
```

it should be enough.

**Comment by Personuo** [comment]
thank you, this is  very easy to custom.

**Comment by theor** [comment]
If you can show what you're making with it, please do!

**Comment by Personuo** [comment]
Yeah,but this may take a few months, and this burst  expressions  is an important part of my new project.
Specifically, it's still in the planning stages and I'm still thinking about how to make it happen。
